// ============================================================
// COMPUNIL — Demo Seed Data (development / fallback)
// ============================================================

import type { Product, Category } from '../types'

export const MOCK_CATEGORIES: Category[] = [
  { id: 'laptops',    name: 'Laptops',       nameAr: 'لابتوبات',        slug: 'laptops',    icon: '💻' },
  { id: 'components', name: 'PC Components', nameAr: 'مكونات الكمبيوتر', slug: 'components', icon: '🖥️' },
  { id: 'gaming',     name: 'Gaming',        nameAr: 'الألعاب',          slug: 'gaming',     icon: '🎮' },
  { id: 'networking', name: 'Networking',    nameAr: 'الشبكات',          slug: 'networking', icon: '📡' },
  { id: 'cctv',       name: 'CCTV',          nameAr: 'كاميرات المراقبة', slug: 'cctv',       icon: '📷' },
  { id: 'services',   name: 'Services',      nameAr: 'الخدمات',          slug: 'services',   icon: '🔧'  },
]

const base = 'https://images.unsplash.com/photo-'
const imgs = {
  laptop1:  `${base}1496181133206-80ce9b88a853?w=600&q=80`,
  laptop2:  `${base}1541807084-5c52e6e76cf3?w=600&q=80`,
  gpu:      `${base}1591488520741-b44a6a8c4c00?w=600&q=80`,
  ram:      `${base}1562976540-1502c2145910?w=600&q=80`,
  keyboard: `${base}1618384887929-16ec33fab9ef?w=600&q=80`,
  mouse:    `${base}1527814050087-3793815479db?w=600&q=80`,
  router:   `${base}1558618666-fcd25c85cd64?w=600&q=80`,
  cctv:     `${base}1558618047-3b6e4b3d3db3?w=600&q=80`,
}

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'ASUS VivoBook 15 X1502',
    nameAr: 'لابتوب أسوس فيفوبوك 15',
    description: 'Powerful everyday laptop with Intel Core i7, 16GB RAM, 512GB SSD. Perfect for work and entertainment.',
    price: 28500,
    originalPrice: 32000,
    category: 'Laptops',
    categoryId: 'laptops',
    brand: 'ASUS',
    images: [imgs.laptop1, imgs.laptop2],
    stock: 15,
    rating: 4.5,
    reviewCount: 48,
    isFeatured: true,
    isOnSale: true,
    specifications: [
      { label: 'Processor', value: 'Intel Core i7-12700H' },
      { label: 'RAM', value: '16GB DDR4' },
      { label: 'Storage', value: '512GB NVMe SSD' },
      { label: 'Display', value: '15.6" FHD IPS 144Hz' },
      { label: 'GPU', value: 'NVIDIA RTX 3050 4GB' },
      { label: 'OS', value: 'Windows 11 Home' },
    ],
    tags: ['laptop', 'asus', 'gaming', 'i7'],
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Lenovo IdeaPad Gaming 3',
    nameAr: 'لابتوب لينوفو آيديا باد جيمنج 3',
    description: 'Budget gaming laptop with AMD Ryzen 5, RTX 2050. Great entry-level gaming machine.',
    price: 22000,
    originalPrice: 25000,
    category: 'Laptops',
    categoryId: 'laptops',
    brand: 'Lenovo',
    images: [imgs.laptop2, imgs.laptop1],
    stock: 8,
    rating: 4.2,
    reviewCount: 32,
    isFeatured: true,
    isOnSale: true,
    specifications: [
      { label: 'Processor', value: 'AMD Ryzen 5 6600H' },
      { label: 'RAM', value: '8GB DDR5' },
      { label: 'Storage', value: '512GB SSD' },
      { label: 'Display', value: '15.6" FHD 120Hz' },
      { label: 'GPU', value: 'NVIDIA RTX 2050 4GB' },
    ],
    tags: ['laptop', 'lenovo', 'gaming', 'amd'],
    createdAt: new Date('2024-02-01'),
  },
  {
    id: '3',
    name: 'ASUS TUF Gaming RTX 4070 Super',
    nameAr: 'كارت شاشة آسوس RTX 4070',
    description: 'Top-tier GPU for 1440p gaming. Supports DLSS 3, ray tracing, and 4K gaming.',
    price: 42000,
    originalPrice: 47000,
    category: 'PC Components',
    categoryId: 'components',
    brand: 'ASUS',
    images: [imgs.gpu],
    stock: 5,
    rating: 4.8,
    reviewCount: 21,
    isFeatured: true,
    isOnSale: true,
    specifications: [
      { label: 'VRAM', value: '12GB GDDR6X' },
      { label: 'Core Clock', value: '2475 MHz Boost' },
      { label: 'TDP', value: '220W' },
      { label: 'Outputs', value: '3x DisplayPort 1.4, 1x HDMI 2.1' },
    ],
    tags: ['gpu', 'rtx4070', 'gaming', 'nvidia'],
    createdAt: new Date('2024-03-10'),
  },
  {
    id: '4',
    name: 'Corsair Vengeance RGB 32GB DDR5',
    nameAr: 'رام كورسير فينجنس 32 جيجا',
    description: 'High-performance DDR5 RAM with RGB lighting. 6000MHz speed for maximum performance.',
    price: 8500,
    originalPrice: 9800,
    category: 'PC Components',
    categoryId: 'components',
    brand: 'Corsair',
    images: [imgs.ram],
    stock: 20,
    rating: 4.7,
    reviewCount: 65,
    isFeatured: false,
    specifications: [
      { label: 'Capacity', value: '32GB (2x16GB)' },
      { label: 'Speed', value: 'DDR5-6000' },
      { label: 'Latency', value: 'CL30' },
      { label: 'Voltage', value: '1.35V' },
    ],
    tags: ['ram', 'ddr5', 'corsair', 'rgb'],
    createdAt: new Date('2024-01-20'),
  },
  {
    id: '5',
    name: 'Keychron K6 Pro Wireless',
    nameAr: 'كيبورد كيكرون K6 برو لاسلكي',
    description: 'Compact 65% mechanical keyboard with hot-swap switches, RGB backlighting, and wireless connectivity.',
    price: 4200,
    originalPrice: 4800,
    category: 'Gaming',
    categoryId: 'gaming',
    brand: 'Keychron',
    images: [imgs.keyboard],
    stock: 30,
    rating: 4.6,
    reviewCount: 89,
    isFeatured: true,
    isOnSale: true,
    specifications: [
      { label: 'Layout', value: '65% Compact' },
      { label: 'Switch', value: 'Hot-swappable Gateron Red' },
      { label: 'Connectivity', value: 'Bluetooth 5.1 + USB-C' },
      { label: 'Battery', value: '4000mAh' },
    ],
    tags: ['keyboard', 'mechanical', 'wireless', 'gaming'],
    createdAt: new Date('2024-02-15'),
  },
  {
    id: '6',
    name: 'Logitech G502 X Plus',
    nameAr: 'ماوس لوجيتك G502 X Plus',
    description: 'Iconic gaming mouse with HERO 25K sensor, 89g ultra-lightweight design, and LIGHTSPEED wireless.',
    price: 3800,
    originalPrice: 4500,
    category: 'Gaming',
    categoryId: 'gaming',
    brand: 'Logitech',
    images: [imgs.mouse],
    stock: 45,
    rating: 4.8,
    reviewCount: 112,
    isFeatured: true,
    specifications: [
      { label: 'Sensor', value: 'HERO 25K' },
      { label: 'DPI Range', value: '100–25,600' },
      { label: 'Weight', value: '89g' },
      { label: 'Battery Life', value: '140 hours' },
    ],
    tags: ['mouse', 'logitech', 'wireless', 'gaming'],
    createdAt: new Date('2024-03-01'),
  },
  {
    id: '7',
    name: 'TP-Link Archer AX73 WiFi 6',
    nameAr: 'راوتر TP-Link آرتشر AX73',
    description: 'AX5400 WiFi 6 router with 6 antennas, beamforming, and OFDMA technology for whole-home coverage.',
    price: 6200,
    originalPrice: 7000,
    category: 'Networking',
    categoryId: 'networking',
    brand: 'TP-Link',
    images: [imgs.router],
    stock: 12,
    rating: 4.4,
    reviewCount: 37,
    isFeatured: false,
    isOnSale: true,
    specifications: [
      { label: 'Standard', value: 'WiFi 6 (802.11ax)' },
      { label: 'Speed', value: 'AX5400' },
      { label: 'Coverage', value: '250 m²' },
      { label: 'Ports', value: '1x WAN, 4x LAN Gigabit' },
    ],
    tags: ['router', 'wifi6', 'networking', 'tp-link'],
    createdAt: new Date('2024-01-05'),
  },
  {
    id: '8',
    name: 'Hikvision 8MP 4K CCTV Kit',
    nameAr: 'كاميرات هيك فيجن 4K مجموعة 4 كاميرات',
    description: 'Professional 4K CCTV system with 4 cameras, 1TB DVR, night vision, and mobile app monitoring.',
    price: 12500,
    originalPrice: 15000,
    category: 'CCTV',
    categoryId: 'cctv',
    brand: 'Hikvision',
    images: [imgs.cctv],
    stock: 7,
    rating: 4.5,
    reviewCount: 28,
    isFeatured: true,
    isOnSale: true,
    specifications: [
      { label: 'Resolution', value: '4K 8MP' },
      { label: 'Night Vision', value: '60m IR range' },
      { label: 'Storage', value: '1TB HDD DVR' },
      { label: 'Cameras', value: '4 units' },
    ],
    tags: ['cctv', 'security', 'hikvision', '4k'],
    createdAt: new Date('2024-02-20'),
  },
]
